import mongoose from "mongoose";

const MovementSchema = new mongoose.Schema({
  participant_id: { type: String, required: true },
  session_id: { type: String, required: true },
  condition: { type: String },
  block_id: { type: String },
  mapping_type: { type: String },
  trial_id: { type: Number },
  timestamp_ms: { type: Number },
  absolute_timestamp: { type: Number },
  dt_ms: { type: Number },
  canvas_width_px: { type: Number },
  canvas_height_px: { type: Number },
  mouse_x: { type: Number },
  mouse_y: { type: Number },
  mouse_x_norm: { type: Number },
  mouse_y_norm: { type: Number },
  mouse_dx: { type: Number },
  mouse_dy: { type: Number },
  mouse_delta_norm: { type: Number },
  cursor_x: { type: Number },
  cursor_y: { type: Number },
  cursor_x_norm: { type: Number },
  cursor_y_norm: { type: Number },
  cursor_dx: { type: Number },
  cursor_dy: { type: Number },
  cursor_delta_norm: { type: Number },
  mouse_vx: { type: Number },
  mouse_vy: { type: Number },
  cursor_vx: { type: Number },
  cursor_vy: { type: Number },
  cursor_speed: { type: Number },
  cursor_speed_norm: { type: Number },
  target_x: { type: Number },
  target_y: { type: Number },
  target_x_norm: { type: Number },
  target_y_norm: { type: Number },
  start_x_norm: { type: Number },
  start_y_norm: { type: Number },
  distance_to_target_px: { type: Number },
  distance_to_target_norm: { type: Number },
  vector_to_target_x: { type: Number },
  vector_to_target_y: { type: Number },
  velocity_toward_target: { type: Number },
  velocity_perpendicular_to_target: { type: Number },
  angular_error_to_target_deg: { type: Number },
  event: { type: String },
});

export default mongoose.models.Movement || mongoose.model("Movement", MovementSchema);
