import mongoose from "mongoose";

const TrialSchema = new mongoose.Schema({
  participant_id: { type: String, required: true },
  session_id: { type: String, required: true },
  condition: { type: String },
  block_id: { type: String },
  block_type: { type: String },
  mapping_type: { type: String },
  base_rotation_angle_deg: { type: Number },
  applied_rotation_angle_deg: { type: Number },
  rotation_noise_deg: { type: Number },
  task_type: { type: String, enum: ["reaching", "tracking"], default: "reaching" },
  path_type: { type: String },
  wave_amplitude: { type: Number },
  wave_frequency: { type: Number },
  trial_id: { type: Number },
  target_angle_deg: { type: Number },
  target_distance_px: { type: Number },
  normalized_target_distance: { type: Number },
  target_x: { type: Number },
  target_y: { type: Number },
  start_x: { type: Number },
  start_y: { type: Number },
  total_trial_time_ms: { type: Number },
  reaction_time_ms: { type: Number },
  movement_time_ms: { type: Number },
  success: { type: Number },
  initial_direction_error_deg: { type: Number },
  mean_absolute_error_deg: { type: Number },
  endpoint_error_px: { type: Number },
  final_error_px: { type: Number },
  path_length_px: { type: Number },
  ideal_distance_px: { type: Number },
  max_distance_from_ideal_path_px: { type: Number },
  mean_distance_to_target_px: { type: Number },
  area_under_distance_curve: { type: Number },
  mean_velocity_toward_target: { type: Number },
  early_exploration_score: { type: Number },
  correction_efficiency_score: { type: Number },
  straightness_ratio: { type: Number },
  num_direction_reversals: { type: Number },
  tracking_rmse_px: { type: Number },
  ideal_path_points: [{ x: Number, y: Number }],
});

export default mongoose.models.Trial || mongoose.model("Trial", TrialSchema);
